### ISSUE TITLE
React prototype required

### ISSUE THREAD

**Issue by kode-sektor** [chat-loc/chatloc.github.io#34]
Transform whole application into React JS. 

Since the app connects with a DB, socket.io double connection may be worthy of consideration.

**Comment by kode-sektor** [comment]
https://socket.io/docs/#Using-with-Node-http-server

This is a link detailing the behaviour of Socket.io towards Node.

**Comment by amnsworld** [comment]
created new project with react interface. Since it was confusing to convert the existing version of handlebars.

https://github.com/amnsworld/chatapp-react

**Comment by kode-sektor** [comment]
![image](https://user-images.githubusercontent.com/60120856/89702455-6c201480-d90f-11ea-8d12-3af09b4ed031.png)
![image](https://user-images.githubusercontent.com/60120856/89702456-73472280-d90f-11ea-9b47-b38881b3999d.png)

Dependencies and directory structure suggestion for MERN-socket.io combo. 

Link: https://socket.io/docs/#Using-with-Node-http-server
